import request from 'supertest';
import { Express } from 'express';
import { pool } from '../src/db/pool';

/**
 * Shared test helpers for Phase 1 integration tests. These tests run
 * against the real dev PostgreSQL instance (see backend/.env) after
 * `npm run migrate && npm run seed` have been executed, exercising the
 * full Controller -> Service -> Repository -> DB stack rather than
 * mocking the database layer.
 */

export const BOOTSTRAP_ADMIN = { username: 'admin', password: 'Admin123!' };

export function uniqueUsername(prefix: string): string {
  return `test_${prefix}_${Date.now()}_${Math.floor(Math.random() * 100000)}`;
}

export function uniqueCode(prefix: string): string {
  return `TEST_${prefix}_${Date.now()}_${Math.floor(Math.random() * 100000)}`;
}

export async function loginAs(
  app: Express,
  username: string,
  password: string,
): Promise<{ token: string; userId: number; role: string }> {
  const res = await request(app).post('/api/auth/login').send({ username, password });
  if (res.status !== 200) {
    throw new Error(`loginAs(${username}) failed: ${res.status} ${JSON.stringify(res.body)}`);
  }
  return { token: res.body.access_token, userId: res.body.user_id, role: res.body.role };
}

export async function deleteTestUsersByPrefix(): Promise<void> {
  // Test-created Managers/Admins may themselves be `audit_logs.actor_id`
  // (e.g. a test Manager who created a Cashier) - clear those rows first
  // so the FK constraint doesn't block cleanup. This only removes rows
  // generated by this test run's prefix, never real audit history.
  await pool.query(
    `DELETE FROM audit_logs WHERE actor_id IN (SELECT id FROM users WHERE username LIKE 'test_%')`,
  );
  await pool.query(`DELETE FROM users WHERE username LIKE 'test_%'`);
}

export async function deleteTestCatalogData(): Promise<void> {
  await pool.query(`DELETE FROM promotions WHERE name LIKE 'TEST_%'`);
  await pool.query(
    `DELETE FROM stock_movements
     WHERE product_id IN (SELECT id FROM products WHERE sku LIKE 'TEST_%')`,
  );
  await pool.query(`DELETE FROM products WHERE sku LIKE 'TEST_%'`);
  await pool.query(
    `DELETE FROM tax_rates WHERE category_id IN (SELECT id FROM categories WHERE name LIKE 'TEST_%')`,
  );
  await pool.query(`DELETE FROM categories WHERE name LIKE 'TEST_%'`);
}

export async function deleteTestSalesData(): Promise<void> {
  // Sales/payments FK-reference register_sessions and users. Clean them
  // before register_sessions so FK constraints stay satisfied.
  await pool.query(
    `DELETE FROM refunds WHERE return_id IN (
       SELECT id FROM returns WHERE requested_by IN (SELECT id FROM users WHERE username LIKE 'test_%')
     )`,
  );
  await pool.query(
    `DELETE FROM return_items WHERE return_id IN (
       SELECT id FROM returns WHERE requested_by IN (SELECT id FROM users WHERE username LIKE 'test_%')
     )`,
  );
  await pool.query(
    `DELETE FROM returns
     WHERE requested_by IN (SELECT id FROM users WHERE username LIKE 'test_%')`,
  );
  await pool.query(
    `DELETE FROM manager_approvals
     WHERE requested_by IN (SELECT id FROM users WHERE username LIKE 'test_%')`,
  );
  await pool.query(
    `DELETE FROM stock_movements
     WHERE performed_by IN (SELECT id FROM users WHERE username LIKE 'test_%')`,
  );
  await pool.query(
    `DELETE FROM payments
     WHERE sale_id IN (SELECT id FROM sales WHERE cashier_id IN (SELECT id FROM users WHERE username LIKE 'test_%'))`,
  );
  await pool.query(
    `DELETE FROM sale_items
     WHERE sale_id IN (SELECT id FROM sales WHERE cashier_id IN (SELECT id FROM users WHERE username LIKE 'test_%'))`,
  );
  await pool.query(
    `DELETE FROM sales WHERE cashier_id IN (SELECT id FROM users WHERE username LIKE 'test_%')`,
  );
}

export async function deleteTestRegisterSessions(): Promise<void> {
  await deleteTestSalesData();
  // Register sessions FK-reference `users` (cashier_id/closed_by) - must be
  // cleared before deleteTestUsersByPrefix() removes the test users, or
  // the FK constraint blocks user deletion.
  await pool.query(
    `DELETE FROM register_sessions
     WHERE cashier_id IN (SELECT id FROM users WHERE username LIKE 'test_%')
        OR closed_by IN (SELECT id FROM users WHERE username LIKE 'test_%')`,
  );
}

export async function closeTestPool(): Promise<void> {
  await pool.end();
}
